[package]
name = "xero_ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
gpui.workspace = true
xero_core.workspace = true
xero_store.workspace = true
xero_finder.workspace = true
xero_terminal.workspace = true
xero_editor.workspace = true
xero_ide.workspace = true
xero_settings.workspace = true
theme.workspace = true
anyhow.workspace = true
async-channel.workspace = true
log = "0.4"
lucide-icons.workspace = true
nucleo.workspace = true
notify.workspace = true
