[package]
name = "xero_editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ropey.workspace = true
anyhow.workspace = true
thiserror.workspace = true
gpui.workspace = true
theme.workspace = true
tree-sitter.workspace = true
tree-sitter-highlight.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-json.workspace = true
tree-sitter-toml-ng.workspace = true
tree-sitter-python.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-md.workspace = true
pulldown-cmark.workspace = true
xero_settings.workspace = true
log = "0.4"

[dev-dependencies]
tempfile = "3"
