[package]
name = "xero_ide"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
async-channel.workspace = true
tungstenite.workspace = true
uuid.workspace = true
log = "0.4"
