//! Language id and path/name dispatch for tree-sitter highlighting.

#[derive(Clone, Copy)]
pub(super) enum Lang {
    Rust,
    Json,
    Toml,
    Python,
    JavaScript,
    TypeScript,
    Tsx,
    Go,
    Bash,
    Html,
    Css,
    Yaml,
    C,
    Cpp,
    Ruby,
    Java,
    Lua,
    Swift,
    Scala,
    Elixir,
    Haskell,
    Php,
    Zig,
    Make,
    Diff,
    Xml,
    Proto,
    Dart,
    R,
    Nix,
    Solidity,
    Ocaml,
    CSharp,
    Cmake,
    Glsl,
    Regex,
    Jsdoc,
    Ini,
    Scheme,
    Powershell,
    Elm,
    Svelte,
}

pub(super) fn lang_for_ext(ext: &str) -> Option<Lang> {
    Some(match ext.to_ascii_lowercase().as_str() {
        "rs" => Lang::Rust,
        "json" | "jsonc" => Lang::Json,
        "toml" => Lang::Toml,
        "py" | "pyi" => Lang::Python,
        "js" | "mjs" | "cjs" | "jsx" => Lang::JavaScript,
        "ts" | "mts" | "cts" => Lang::TypeScript,
        "tsx" => Lang::Tsx,
        "go" => Lang::Go,
        "sh" | "bash" | "zsh" => Lang::Bash,
        "html" | "htm" => Lang::Html,
        "css" => Lang::Css,
        "yml" | "yaml" => Lang::Yaml,
        "c" | "h" => Lang::C,
        "cc" | "cpp" | "cxx" | "hpp" | "hh" | "hxx" | "h++" => Lang::Cpp,
        "rb" | "rake" => Lang::Ruby,
        "java" => Lang::Java,
        "lua" => Lang::Lua,
        "swift" => Lang::Swift,
        "scala" | "sc" => Lang::Scala,
        "ex" | "exs" => Lang::Elixir,
        "hs" | "lhs" => Lang::Haskell,
        "php" | "phtml" => Lang::Php,
        "zig" | "zon" => Lang::Zig,
        "mk" => Lang::Make,
        "diff" | "patch" => Lang::Diff,
        "xml" | "xsl" | "xsd" | "svg" => Lang::Xml,
        "proto" => Lang::Proto,
        "dart" => Lang::Dart,
        "r" => Lang::R,
        "nix" => Lang::Nix,
        "sol" => Lang::Solidity,
        "ml" | "mli" => Lang::Ocaml,
        "cs" => Lang::CSharp,
        "cmake" => Lang::Cmake,
        "glsl" | "vert" | "frag" | "comp" => Lang::Glsl,
        // .env / secrets.env use the same KEY=value shape as ini (no dedicated dotenv grammar).
        "ini" | "cfg" | "conf" | "editorconfig" | "gitconfig" | "properties" | "env" => Lang::Ini,
        "scm" | "ss" => Lang::Scheme,
        "ps1" | "psm1" | "psd1" => Lang::Powershell,
        "elm" => Lang::Elm,
        "svelte" => Lang::Svelte,
        _ => return None,
    })
}

pub(super) fn lang_for_name(name: &str) -> Option<Lang> {
    let name = name.to_ascii_lowercase();
    let name = name.split_whitespace().next().unwrap_or(&name);
    Some(match name {
        "rust" | "rs" => Lang::Rust,
        "json" | "jsonc" => Lang::Json,
        "toml" => Lang::Toml,
        "python" | "py" => Lang::Python,
        "javascript" | "js" | "jsx" => Lang::JavaScript,
        "typescript" | "ts" => Lang::TypeScript,
        "tsx" => Lang::Tsx,
        "go" | "golang" => Lang::Go,
        "bash" | "sh" | "shell" | "zsh" => Lang::Bash,
        "html" | "htm" => Lang::Html,
        "css" => Lang::Css,
        "yaml" | "yml" => Lang::Yaml,
        "c" => Lang::C,
        "cpp" | "c++" | "cxx" => Lang::Cpp,
        "ruby" | "rb" => Lang::Ruby,
        "java" => Lang::Java,
        "lua" => Lang::Lua,
        "swift" => Lang::Swift,
        "scala" => Lang::Scala,
        "elixir" | "ex" => Lang::Elixir,
        "haskell" | "hs" => Lang::Haskell,
        "php" => Lang::Php,
        "zig" => Lang::Zig,
        "make" | "makefile" => Lang::Make,
        "diff" | "patch" => Lang::Diff,
        "xml" | "svg" => Lang::Xml,
        "proto" | "protobuf" => Lang::Proto,
        "dart" => Lang::Dart,
        "r" => Lang::R,
        "nix" => Lang::Nix,
        "solidity" | "sol" => Lang::Solidity,
        "ocaml" | "ml" => Lang::Ocaml,
        "csharp" | "c#" | "cs" => Lang::CSharp,
        "cmake" => Lang::Cmake,
        "glsl" => Lang::Glsl,
        "regex" | "regexp" => Lang::Regex,
        "jsdoc" => Lang::Jsdoc,
        "ini" | "env" | "dotenv" => Lang::Ini,
        "scheme" | "scm" => Lang::Scheme,
        "powershell" | "ps1" => Lang::Powershell,
        "elm" => Lang::Elm,
        "svelte" => Lang::Svelte,
        _ => return None,
    })
}

/// Basenames without (or ignoring) extension.
pub(super) fn lang_for_basename(name: &str) -> Option<Lang> {
    match name {
        "Makefile" | "makefile" | "GNUmakefile" | "gnumakefile" => Some(Lang::Make),
        "CMakeLists.txt" => Some(Lang::Cmake),
        "Cargo.toml" | "rust-toolchain.toml" => Some(Lang::Toml),
        ".gitignore" | ".dockerignore" | ".editorconfig" => Some(Lang::Ini),
        // `.env` has no extension; `.env.local` / `.env.example` use a non-env suffix.
        n if n == ".env" || n.starts_with(".env.") => Some(Lang::Ini),
        _ => None,
    }
}
