[package]
name = "xenon_design_system"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
visual-tests = ["gpui/test-support"]

[dependencies]
gpui.workspace = true
theme.workspace = true
lucide-icons.workspace = true
xenon_settings.workspace = true
unicode-segmentation = "1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.2.2", features = ["NSAccessibility", "NSWorkspace"] }
